* Configurations
** api.requests.schema.json
   Using http://json-schema.org/.

   This aims to be a description of the "requests" argument object
   used in the Barista/Minerva request protocol. This does not contain
   information about the other parts of the protocol (e.g. "token" and
   "intention").

   This may be used in the future as a basis for a Swagger
   description.
** api.response.schema.json
   Using http://json-schema.org/.

   This aims to be a complete description of the responses that one
   would expect from Minerva/Barista; remember, this is slightly
   different from a pure Minerva response, as Barista may have added
   certain items (e.g. "uid", etc.).

   This may be used in the future as a basis for a Swagger
   description.
** api.swagger.json (TODO)
   May eventually contain the Swagger description of the Noctua stack
   API.
** app.json
   A configuration file to describe instances of Minerva (or other
   federated clients), mostly their URLs and permissive paths.
** auth.json (DEPRECATED)
   An early version of users.json.
** users.json
   A downstream version of geneontology/go-site's metadata/users.yaml
   (literally
   https://s3.amazonaws.com/go-public/metadata/users.json). Required
   for Barista authorization checks.
